spring:
  datasource:
    url: jdbc:h2:mem:book
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto:  none
  h2:
    console:
      enabled: true
      path: /h2-console

flyway:
  enabled: true
  
server:
  port: 9090

logging:
  level:
    org:
      hibernate: INFO

