spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abhi
  jpa:
    hibernate:
      ddl-auto:  none
  
server:
  port: 9090