create database mydb;

use mydb;

CREATE TABLE BOOK (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255),
  DESCRIPTION VARCHAR(255),
  AUTHOR VARCHAR(255),
  PUBLISHER VARCHAR(255),
  PRIMARY KEY (ID)
);
